### ISSUE TITLE
Markup not visible after cloning of scene loading

### ISSUE THREAD

**Issue by cpinter** [SlicerHeart/SlicerSurfaceMarkup#1]

**Comment by lassoan** [comment]
Do you mean the control points are not visible?

**Comment by cpinter** [comment]
I can't remember, it was quite broken though. I can check it out if you want.

For now I'm looking at fitting surface on arbitrary model. A grid with known size is needed unfortunately.

**Comment by lassoan** [comment]
I cannot reproduce this issue anymore. Tested both with local builds and the latest official build.

The case that I've come across was due to glyph scale was set to 0 (probably intentionally, just to improve visual appearance).

It works well even if I specify a scene as command-line argument when starting Slicer (so there is no issue with registering the node type or widget too late).

I close this and we can reopen if we encounter it again.

**Comment by cpinter** [comment]
Great, thanks!
